import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import loadedProductsFromJS from "../src/data/products";
import ProductContainer from "../src/components/ProductContainer";

const Home: NextPage = (props) => {
  // console.log("index page here");
  // console.log(props);
  const [loadedProducts, setLoadedProducts]: any =
    useState(loadedProductsFromJS);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" w-full flex items-center">
        <div className="absolute flex flex-col p-3">
          <h1 className="font-bold text-4xl text-red-600">Proudly Canadian!</h1>
          <h2 className="text-2xl font-semibold text-white">Print Everything with high quality at reasonable price!</h2>
        </div>
        <div className="w-full h-96 bg-slate-600"></div>
        {/* <img className="w-full" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIQEBUSEhIQFRUVFRAQEBUVEhAVDxUPFRUWFhUVFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGi0dHx0tLS0tLS0tLS0tLS0tLS0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAJ8BPgMBIgACEQEDEQH/xAAcAAAABwEBAAAAAAAAAAAAAAAAAQIDBAUGBwj/xAA+EAABAwIEAwUGBAQFBQEAAAABAAIDBBEFEiExBkFRE2FxgZEHIjJCobEUI8HRFVJi8HKCkqLhFjNDVXNE/8QAGgEAAwEBAQEAAAAAAAAAAAAAAAECAwQFBv/EADgRAAICAQICCAQEAwkAAAAAAAABAhEDEiEEMRNBUWFxgbHRIjKhwRSR4fAzgvEFI0NEUnKSssL/2gAMAwEAAhEDEQA/AOINRogjWiEGUAiRtCBAQKIoyqsAIkZRJAJKCNGpGEjQQTAAOq2lC67RtsFi1rcCfmjbbwPkoycjbA/iLunb1VhBHzUGmCtKdtlxSPVxofjYpAaihClNYsmzdESSK4VY6UfC7yKv8io62k94/RVFmcywo4g9trbbHuTrYLKuwycxmzhpt3ghXrSDqNUmJMj9klCNS2RJfYrM0I3ZpJiUoRoxEgCEYUh0SsxEkvhTArGxqPiGGCVpHNXQp0fZW2VJ0TJKWzOZVWBuDrZTvZQa3By37DvXU56QHUqtqaNpN7DTZbrMzjfCRfI5jNh7mXuPFRyMjSfQd60GOYgx0hjbb3fiI2zdPL7qm/Dl5v6LtxRlLmeXxE4Y5UnZTvBJuUnIVeOw89EkYeei06M5/wAQik7MoZFdvoSBso/4VHRjXEIrhEUoQlWLKdPik7k9AnnKJBBBZnSBGESCaEBGiCNNAAokaJIAIIIJAAII0SAAr/hqbdvfmH6qgU7B5ssze/QpSVqi8bqSZvqY7d6tYGqpodbBXcEa4Jns4uRLhapUaZjan2LFm6YRKZljDlJy3SXQnu/VCBpMopWFhNz5fKRy16jqlOqi0g5hbY/DmB6GysKimLtrHf6qomoMpF+XTn/ZutE0+ZjKDXI0+FVjXi19VZdnoueSl8Tw+LNfm3u/vktxw/ijKllwRcfEOhScCNVPckmFDIphakOjU6S1MjZUsRJ9saMgJ0JyGciQ9gT5SJpWxtLnaAC5KaQrohyQX3XOuMuLGtzQUxu7USSg6Dq1nf38uXcri/iKeqvFFmjh2NtHv/xHkO5Yw4Y7oV24uGreR5ef+0Iu4xfmIoW3K1eG0gICq8Nwp1wbLV0NMWhdTdI82K1SsjyUYTJpgrSZqiuCSLaRBlgFlXSUwVxM1M9mqTM3Gysjpu5PiFT2QpRiQ2LQc3QQQWR2gQQQTACF0EEABBBBABokaJIA0SNEmgAlRusQehBSU7Gy6Egs6HhUmaNrx0BVrFX25LKcL1gyGMnUbeCvm7LhyRptM9bBPVBNF7T1zXeKkicLMyOLW5m7j7KTS4hmaHArGUes6FPqZffiE3+PZtmb4XVRLU3G6p44De/efukoJluXYa90x5f8JGpVPS1hZoTp3q1jmuEVRSkMzu5AfupGDYe5j+0j0OoI5G/O3VKp6fM7UKyqK2KjizyOa3e1yhXyROSqss2VXJ9we/8AdSGPBXHeI+Ony3ZBdoO8h+I/4RyVDh3E1TBfLNLa22Y7+C6Y8PNrc86fFY06W56DAuk5Fxil4+rNPzHHXUWYfDWy0OGYpWVHxSSAHvyi3gFM8TirZUeIjN1E6HI5oOXd3Qb+fRCspmuZY+aqsJpsguTc7nxVwASuZyvkbNdphcUwYBxICrm4eOi6FU0ocFlsSi7M7Lvw5tWzPM4jh9L1LkQoKcDkpOgUcVITM1Qtzm2DmkCjlwTUj0w56pGbY9KAm8oUZ8pTZnKohss2jRJcFBFUkurUqDUYFGiQUHYBBBBMQEEEEABBBBAAQQQSACCMBW+HYBPMMzYn5f5sjsnraydA2V1PAXmwF1pWYGWRZnDXktLw5w4yEZn6uUzGIgQUuk3pGcouStnNY5nQyBw5H6LZ4fiLJm3aR3jmCspi9NZxVYyRzDdpIPcUsuNT7jThuIlBbbnSL30Va+F0TiRsfRZylx6ZuhdfxCu6DFzJo7/hYrDLuOx8dBc0yeyTOPdHiL6hSqBx1B8R4p2jazcDVSiGjkFm8TLXGxW9Mh9kS4eOquqOE6BRaexctBTZWNuSBbU3WMk06Z3wmpx1R6xFTO2mhdK7YDzJ5AeawNU410uaR2vyj5WjoAp3GWOfiCIo7mNpuSPmd3dwVNTU8lwWtdfwWsIuO/Jnm8TmU5aeaX1JlRwPmF2XCr/+ipAdbroHD0spaA9pHirSZgvsh8RkjsyocPiluvUxuBcGtaQSLlbihwfKNApdAwK4pwsW5ZHuzdRjjXwoqm0ZanW6K4MYKjy0yTxtAshBVLxBTgtJVzMC0qsxo/lHwRF07HJKSpnO5KoAkdEk1YWZxWsImcO9QziJ6r1klR4D13yNeakJLpgsmMRPVOtxE9VVIluXYaF7gmHFU4xA9UPxydEtvsLN7lHe9Q/xiI1KfInfsKJKVzLgZ1yu8jofpf8AsqGcKmy5g3MP6Tc+g1XPZ6NEJBPdg6x90gi1wQdjf9kyFQgIKWKGT5WX66tJA8L6Jl1O4X023sQSPIJWA0grHD8EqKg2ihkeedmmw89lt8E9lcj/AHqqURD+RlnSeZ+EfVTLJGPNlwxTn8qOcAX28B1utdgHs9raqzizsYz88t2kj+lnxH6Lr2A8M0lEB2MTc3OR3vSn/MdvJWzZ7HVYS4jsR1Q4Tt3Mrw17MqSmIfLeokGt3i0QPczn5krfQNyiwAAGwG3om4agEck+wJXq3uynFR2Sorq7AYJrmxa7mWaeo2KzWMcJSgXjIk7vhf8AsVtn3GvqjD7pp0Zygpczz7xHh7mXztc09HAg/VY6VlivV9XQxTNyyMY8dHNB+6xWN+zOmku+AZHfyX/LPhfZbrLtTOR8O024b93I4EArLDQ4kWBXTI+BGtNnsIPh9ld0HCUTNm/RV0i6jKWObVNUY3C6aUjYq1/hMrlu6fCWt2H0UoUQ6LK2y1CjB02APvckq3Zw/nFnkuHQk29FpTS25I+zcOSVNlrZUU1NwzCPkHorWHBox8o9ErM8cinWvf0KekLHI8OaNgFTY5G2O3VWxnc0XI2XOuI+I88xAOjdPNZ5VtRvg+buNVQ1AAVtT1IOy5tQY0Xuyha/DJrhcu8dj0nBNWjUMlunbqop5iXWVnGtouzmnDSQ8SFtVSVcZkaQFpqiDM2xUClpMpN0tDciXk0xOS4xwI97y5pOqpKngidu2vku+vpx0UeSiaeQXXbR57iuZ54k4XqG/Ko0uETN3YV6Hkwxh5BQ58DjPyhPUGjvPPEkD27tI8khod0Pou8TcJxP3aPRLh4OgaNGD0VpompdxwW7huD6JPaFd2q+DYXD4B6KiqvZ9EToLJ2hU+wvpcFhd8UbDbUECx8NFGfwvGSHMfI09CQ4X89fqrVmtrbn9ApIh2814ylJcmfQyhHrRl6rgvtQfzh5xgga30sVCpvZqGkuMzRqbflnMARte4HnbZbljreGyW03WizT5WYSwY27aMrS8DMabmZ/L4Q4C/PQuO/NXEHCVK12Yxh7uZfrfnr181btTrTdVqk+bDTFckJhhbGMrGtaOQaAG+gTjGdUBulOsgLHWwgpz+HhNUzrHVWLJAtYpNGc5SjyIjabLsnmyDmnrqNW0pcLsNncuib2WxN6n8TJLZEoxgqlE8kZtI0jv3b6qwpKsHmlGcXswnilHdfQkFjhtqkmbqpLXApMsIK0ca5GSmr3GXsBGtijip2pqNpBsVItzCUZMMkE+QYhCV2YXMca9pz4p5IWthiLHvZlnjmLiGuIDiWuAANrjuITcXtMqToKeGZ3IQmTUeALuS3Vs5G6Op9mEfYhcypvay1rstTR1MR/p976PDFu8ExuGsi7WFxc25abtc1zXDcOadQdR6p0xKSZZdiEDEEQegXpUMp+JK1kFPJI6wAaV5/E+d5N9ySupe1/EgKdsLT7zyCR/QP+bLjdE4iRS9zWFpGnwo2ct5h0+Vlyue4bLYhXWM4kY42AfMQFyTTbPUxySjubvCavMbrSRP0WK4Zk90E9yv8AHK7sKftByLfqbKYOk2GWOqSXaXgek2UPDqnO0HqAVNYAVtB2rRyThVpiCkOCccE24Lo5nG1Ww24Jp7U8UhwQIZvZIM6W8Jh4QAp1SE06oCakaoj2osdC6JgLh5KZIyyqcPm0HcrlpuF50Yqj2JumRg1GBYJxzBZQKieyKoE7J0OuylMYqqGosFNgqwQqTRMosnBgS44Qo8UoUuCULRJGTtAfAkCbLupoN1Er6TM023VSTW6JjJPaQttUE82UFYd2JGJxa8kWNiDuragxIPF2kEdxWUc2+5vPhWt0ahpDtDYpiXC23uz3T/t9FEpqtWUNQtlplzOZ68b+Ejte5nxDz5JxlUnpi1zbFVMbbc+qG2tkEUpbtUP1NVZ477qZE+4WWxetbHJEHOAzFwFzYX0sFc0FTcLOM/idms8VwTRivatwY2pH4yM5ZGANmsGkPiGznXcAMvXp4LmEWBPuC2el7j22V32/VekJbOBaRcEEEHYg7hcYxKjjgqZITDGQxxDTkbqw6tO3QhdWLI1aSs8/iMa2k+vYzE+D1Lzlux9trTxu+7ltuA8dZhcToZ2SkSSZy6Nj5GxnIAM1m87H4bnRQBQQEX7GP/SB9kRw6nG8TPV37pS4iMtmn+/Mzjgkt1X5v2OvUuJMkaHMcCCLg9Qq3iDiqCkYczgX291g1cSuQ1vFL4h2NPaNjbgBt+tzv3k+qz81cXEuc4uJ3JNypg59fL6m2mPaWmNYpJVSulkOpOg5BvIBVcLLOuoz6pTKd7bN1969z4K6opyVpI0GDU2Yi4U/HacEAdNQjwORuig8T4gGThnUN+q547zO7JJRxbm64WgJY3wC1woGzNMTxcFp0KouEh+W3wCseI8Z/Axdta9iG28UYtviJ4iTdx7heCwGO8Tt2HL4jkfRW7xbVZbhrHhWyPmAIFw2x3uAtNNJ7qcUoppdRnNuTUu1IcjcC63VOywt6qBTyB7bg6rCcU4tWQylmcBp1aQNbdFtid7HHxWnEnOTpLmdAdEORTL4iOS5dS8U1UZ/7gd3EX+yv6Ljh3/kjv3tK2cWuZx4+LxZXUG5eCb9EaxwUd4TNDxJBNodD/UCCp7mxu2cPVQqfLc7JY5w+ZNeKK+QKM8KxlpHctfBQpGEbiyQjJUWLCysWYxpuua0uKd6tqbEAea5XiZ6sM0ZI3f8TuN1EfU5iqCGsB5qyotVm40UmWcLypUYKagjUpjFKQ9QuN5VhSz9VDbdOxtVrYl7l1FMpMcioQ9ylw1XVaKZjLFtsKxzAIqthDxY8nN0cPNc9xXDKnCWOlaHSsB0bG1xNv5pP5QO6/luumw1CffZwsbG6uovqshTnDazCcOcRRVbA5jxm5tuMwPgtNBMVzrinhllJiMc0IysmLszRoBILajoDf6Lf4b8I8lg1plSOly1w1NE50xtZIZo258SoPEGKMpIHTSEADQAm13HYBc44g4//ExGJjuya4WcYyTIRzAcQLLeOOUuRwZ+Kx4tpXfYk36KvzaI/HuMCo7QxvaQz4CCPlO481vODsWFVTRy8yLPHR7dHf33riVdBGIyW9rysSLN3Wn9m2MupXe8x5heS2Rw+Frhs703VZMKjHZ8h8NxOTLOtDV7VT6uTrs6jttOcy5H7UK58OIOa1wF2ROPW9iPsAuoxYlCyLte1j7O2YOztII7uq4zxT21dVyThrQ1xAYMwJEbRZt7HfS/mlhcU9zTiMObJF9FFvw9yikxaU/OVGkrpD8zlLfhUg3IHkmH0lt3fQrtjFv5Yt+TPLljyR+dpeMl7lVK5xKQbqf+BudMx8AU+zBZDtDKf8jlMoOO8lXjt6lxafKS8t/QqmOIUqjk98KyZw7UHaB/np904OF6se8IttbAgn0WMs2JbOcV/NH3LjB3at+T9jQ4HTF1iASovG1NlngcefunyIWs4OpmgjPdm1w4EH6pzj7h91REHQAu7J+clupy21XNCS1pnq5lHoml3P68jQcOHLG2x0sFG9pJzUDj0fGfqpfDLfyIjobtBVtimGMqYzDILtfYH9FGNNKwz6XJ+DML7MZQGvbcbh3guike6slgvDX8PqHssAx4ux3Ikcj3rZRgGK9xfotErk+rxM20oR+36mSwXFvzZIj8j3N8r6KwxbDo6kDMPh2V1NgMUzWvtlfycND59UyMGmbs5pHmClHHKPevH+gLPjfN012rb7lHDwueUQ83H9FLi4Zd/Q3wbc/VammYWsAcbkDVLLgupWuSS8vezllxWd7dI68a9KM43hdvzPd5WH2SW0FNCdAS7/MStKUw8N3936Km5vZyf78Dne/Pfx39SHSVIfoGuHiEctPc7BPPqWDmFHfiUY5lJJIZ5OzOHMpyOre3ZxWzi4cpf5ZD5SKWOFIHDSCc+DZFv+Hy9ca8Wl6s20cOv8xj8tb9IGQpsbe3dajA+LWAgPPmmqngWV3/AGoZx/iaSFVz8EVzf/zvI7rfa6wzY4xX944r+aPuTDiXqqEtXlL/ANJHUsPxiF40e31VrHWM6hcJOE1UR+GRh8S1Oh1YNO0kH+Zcaxx6pp+Z1fib5xZ26pxeGMZnPaAOpAWWxL2mwRktiY+QjmLBl/E7rmMtJK83e4nxJP3Rtw7qT6LWOOHW78LM5cTJ/KqNdN7Uaon3YogL95NlteGONaess1xEcvNp2J/pPNchbh7f6k9HRNBuAbjY3N03CD5J/l7sUc2S99/33HoO5CfhqCuRYDxdUU9muJkZtZx94DuK0FTx6S20cRDurjoPIbrJQl2HR0kGi04qrY3zsZqXMFyA1ziC7bz0VphmIOygCnqCf/m4D1IXM21sxeX535ibkgkaq4osdqmbSvPcdVXxL/Di+9zl6KKX1ZnKWSS0qdL/AGr1bZfcScPT4kW9pTzNay+Romja0E/MQ4alUE/stmAJZ7psbB0kZ16aBajC8Wr5NowR1c0tCvmy1ltWRf6iP0XSsuTTUYY4+UpeszilinfxZZP/AIR/6wX1bZ57x6jqYBkmDg2+W2tsw5dxHQqFh9W4NMYNs+mrb7i2h5LrXG3D1VVEuELbkWcLizwNr945HcLEP4DqmGO0NQ4lrHkCJ1mvvqwu2JFt+9XjbXZ+VfT9RZJS62333f78OXcNGgc6C8cb3uJcGgR/lgA2uX9oNdNsp5Kuiw2uB0jePNn6ldPwOgr6SNkf4N0gsXFrqeJ1iSSfzO0aT17r2V9FUV3/AKeM9+eNg+5VrJNcnXmYrFjaqSvy9zj8or6RzHyhoB1YJRG6F9t2kj3fK4K6twbjdDWtyOp4aeoaLvicxgDh/PE63vN0PePDVKxX+IVERifg8JY7Qh1Sy3juLHoeSx7/AGd1Tmta6ldZt8rXV1PpfU2ysWeaCz/xXfm/cvHFY/4ca8v0OqfgoCbNMVxuAW3t4BRn08GbJ72boGSfe1lL4XoOypYmzRRMlaC1wY1ltCQ05mtaLkWvYDdWfaf0n/aP1K5VweBcoR/Jfc6I5Wvmt+Dr7P7FDPhzWtzMic8/yaNd/uISqGieT71N2Y73sc70H7q7MruTWjzJ/QJtxefmA8G/uV0xUYqkl9ftt9DGTk3dv6fdCWUfUD6J5kIA2Fu4KMKd3OSU+Ba0fQJ6OK2xf/rf+6SVFW2MnA4jq0OYd7NJAv4HQKTT4YGEHNIba2JFvslDzRKOjjd0i+lnVamSnOa4WcAfqo7qaH+UeQISUCqaslNrlsPicNFhew2CQ+s7kwU24piFuqXdyafUuPNJcm3IAJ8rup9VHeSnXJh5QxjT1GcpDyozipKI2J42aZ+UUsj+hYBZP0mNzSQucymcHgXax+mbzV61o6J5jVn+Fw/6ETrl2mTbj1cQCKHpcF4vbnbvWriibI0EssSNQbXB6J4JYVrDjXKK/JC1PtK6pwOOTcA+IVNVcDwP+Ro8NPstbmCS6doVKKXJegan2mAqPZ1GfhLh6H7qBL7OH8n+rV0g17RyKQcRPJqdFamcsm9n042yn1CiS8F1Lf8Ax38Cuufi3noEntnn5vojSPpGchj4Wqr6wP8AK37q+wv2fzP1ecg6aXXQbX3JSgP7uUtI+kZjP+gMp1mIHgLq8wbhanhOYkvPUglXTUsFOkS5yfWPwFjBYNJ8glmoFrZPUqOCjQSLMp5NZbvuUQkd1Hk0fqkoIAd7U9SkFx6pKNA7AhZBGgQVkLI0EAFZHZBGEACyLKjQugArIijJSSgAJLigSkEoABKbKNxSHFABOKacUpxTTigBLimXlLeUzI5DGNyFRXOTsjlEcVJR/9k=" alt="describe the image here" /> */}
        </div>
      
    
      <section className="bg-white py-8">
        <div className="container mx-auto flex items-center flex-wrap pb-12">
          <div id="store" className="w-full z-30 top-0 px-6 py-1">
            <h1 className="font-bold text-xl text-center my-4">
              Top Picks from Our Members:
            </h1>

            <div className="flex flex-wrap justify-center	">
              {loadedProducts.map((product: any) => {
                return (
                  <ProductContainer
                    key={product.id}
                    id={product.id}
                    name={product.name}
                    category={product.category}
                    categoryId={product.categoryId}
                    description={product.description}
                    price={product.price}
                    src={product.url}
                  />
                );
              })}
            </div>
          </div>
        </div>
      </section>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
